#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/crashcourse?serverTimezone=UTC
#    username: root
#    password: hongbin1123


# 这两种方式都可以链接数据库，第二种整合了druid
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/crashcourse?serverTimezone=UTC
      username: root
      password: hongbin1123