spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crashcourse?serverTimezone=UTC
    username: root
    password: hongbin1123

#设置Mp相关的配置
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix:

#设置Mp相关的配置
mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_

