#spring:
#  redis:
#    host: 192.168.114.130
#    port: 6379

spring:
  redis:
    client-name: root
    password: hongbin1123
    host: 192.168.114.130
    port: 6379
#    client-type: jedis

 # lettcus?jedis??

 # jedis??Redis??????????????????jedis??????????????????????
 # ?????????????????????

 # lettcus??Netty?????Redis?????????????StatefulRedisConnection?StatefulRedisConne
 # ction???????????????????????????????????????lettcus?????????????